// try{
//     let x = undefined;
//     console.log(x[0])
// }catch{
//     console.log("error handling in catch");
// }finally{
//     console.log("Finally always get executed");
// }
 
try{
    console.log("Hello");
    console.log(a);
    console.log("Ending try")
}catch{
    console.log("Exception handeled");
}

let a =10;
console.log(`a = ${a}`)

